// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qcrnicltqhcdpytucbgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjcm5pY2x0cWhjZHB5dHVjYmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NjI1MjksImV4cCI6MjA3ODAzODUyOX0.WjQI5JxFUi_hAS9aFz7b51SoPW5_9nDW5b68T4IzQik";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});